version: "3.9"

services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    hostname: ${APP_HOSTNAME}
    restart: unless-stopped
    working_dir: ${SRC_PATH}
    build:
      context: .
      dockerfile: php/development/Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
        - USER_NAME=${USER_NAME}
        - SRC_PATH=${SRC_PATH}
    environment:
      UID: ${UID}
      GID: ${GID}
      USER_NAME: ${USER_NAME}
    volumes:
      - ../app:${SRC_PATH}
      - ./php/development/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
